# Generated by Django 3.2.7 on 2021-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Código')),
                ('order_date', models.DateField(verbose_name='Data to pedido')),
                ('order_id', models.CharField(max_length=50, verbose_name='Id do pedido')),
                ('customer_cpf', models.CharField(max_length=20, verbose_name='CPF do cliente')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('used_in', models.DateField(blank=True, null=True, verbose_name='Utilizado em')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-order_date'],
            },
        ),
    ]
