# Generated by Django 3.2.7 on 2021-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='customer_cpf',
            field=models.IntegerField(verbose_name='CPF do cliente'),
        ),
    ]
